unistra_profetes_homepage:
    path:       /
    defaults:   { _controller: UnistraProfetesBundle:Default:index }

unistra_profetes_fiche:
    path:       /diplome/{id}.{_format}
    defaults:   { _controller: UnistraProfetesBundle:Fiche:index, _format: html }
    requirements:
        id:     ^fr-rne-06\d{5}[a-z]-pr-\w+-\w+$
        _format:    html|xml

_unistra_profetes_repertoire_fiche:
    path:       /diplome/
    defaults:   { _controller: UnistraProfetesBundle:Fiche:repertoire }

unistra_profetes_composantes:
    path:       /composantes/
    defaults:   { _controller: UnistraProfetesBundle:XQuery:composantes }

unistra_profetes_composante:
    path:       /composante/{id}
    defaults:   { _controller: UnistraProfetesBundle:XQuery:composante }
    requirements:
        id:     ^fr-rne-06\d{5}[a-z]-or-\w{3}$

