imports:
    - { resource: parameters.yml }

services:
    exist_db:
        class:      Unistra\ProfetesBundle\ExistDB\ExistDB
        arguments:  [ %existdb.wsdl%, %existdb.username%, %existdb.password% ]

    twig.extension.unistra_xslt_extension:
        class:      Unistra\UtilBundle\Twig\Extension\XsltExtension
        tags:
            - { name: twig.extension }

