parameters:
#    unistra_profetes.example.class: Unistra\ProfetesBundle\Example

services:
#    unistra_profetes.example:
#        class: %unistra_profetes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
